/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package cvcm;

import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import java.util.regex.MatchResult.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
/**
 *
 * @author Anshul
 */
public class Center extends javax.swing.JFrame {
ConnectionClass cobj = new ConnectionClass();
    PreparedStatement pst;
    ResultSet rst;
    long cid;
    JTable table;
     JScrollPane pane;
    DefaultTableModel model=new DefaultTableModel();
    /** Creates new form Center */
    public Center() {
        initComponents();
        model.addColumn("CenterId");
        model.addColumn("City");
        model.addColumn("Address");
        model.addColumn("Phone Number");
        model.addColumn("Email");
        model.addColumn("Incharge Name");
        model.addColumn("Timings");
         table= new JTable(model);
        pane= new JScrollPane(table);
        pane.setBounds(500, 200, 750, 300);
        add(pane);
        cobj.connect();
        int j=0;
        try
        {
            pst=cobj.con.prepareStatement("select * from tbCenter");
            rst=pst.executeQuery();
            while(rst.next()){
                model.insertRow(model.getRowCount(), new Object[]{rst.getString(1),rst.getString(2),rst.getString(3),rst.getString(4),rst.getString(5),rst.getString(6),rst.getString(7)});
                j++;
            }
            jLabel9.setText("Total Number of Center "+j);
        }
        catch(Exception ex)
        {
            System.out.println("error in table");
        }
        cobj.disconnect();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        errjLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        adjTextField1 = new javax.swing.JTextField();
        phjTextField2 = new javax.swing.JTextField();
        emjTextField3 = new javax.swing.JTextField();
        injtextfield = new javax.swing.JTextField();
        tmjTextField5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Center");
        setForeground(java.awt.Color.white);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Address");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Email");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Incharge Name");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Timings");

        errjLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Phone Number");

        adjTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adjTextField1ActionPerformed(evt);
            }
        });
        adjTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                adjTextField1KeyPressed(evt);
            }
        });

        phjTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phjTextField2ActionPerformed(evt);
            }
        });
        phjTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                phjTextField2KeyPressed(evt);
            }
        });

        emjTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                emjTextField3KeyPressed(evt);
            }
        });

        injtextfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                injtextfieldKeyPressed(evt);
            }
        });

        tmjTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tmjTextField5KeyPressed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setText("Reset");
        jButton2.setPreferredSize(new java.awt.Dimension(97, 41));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton2KeyPressed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setText("Search");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jButton3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton3KeyPressed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton4.setText("Save");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jButton4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton4KeyPressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("City");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Enter City");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField2KeyPressed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton5.setText("Show");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton6.setText("Refresh");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(errjLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(169, 169, 169)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jButton4))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tmjTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(injtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phjTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adjTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emjTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(124, 124, 124)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(266, 266, 266))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 214, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton6)
                    .addComponent(jButton5))
                .addContainerGap(221, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(adjTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(phjTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(emjTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(injtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tmjTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton5)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton6))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 192, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(errjLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adjTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adjTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adjTextField1ActionPerformed

    private void phjTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phjTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phjTextField2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        cobj.connect();
        if(jTextField1.getText().equals(""))
            errjLabel5.setText("Enter City");
        else
            if(adjTextField1.getText().equals(""))
            errjLabel5.setText("Enter address");
        else
            if(phjTextField2.getText().equals(""))
                errjLabel5.setText("Enter Phone  Number");
        else
                if(emjTextField3.getText().equals(""))
                    errjLabel5.setText("Enter Email");
        else
                    if(tmjTextField5.getText().equals(""))
                        errjLabel5.setText("Enter Timings");
        else
                        if(injtextfield.getText().equals(""))
                            errjLabel5.setText("Enter Incharge Name");
        else
                            if(phjTextField2.getText().length()!=10)
                            {
                                errjLabel5.setText("Invalid Phone Number");
                            }
        else
                        {
                            
                            try
                            {
                                pst=cobj.con.prepareCall("{call prcinsertcenter(?,?,?,?,?,?)}");
                                pst.setString(1, jTextField1.getText().toUpperCase());
                                pst.setString(2, adjTextField1.getText().toUpperCase());
                                pst.setString(3, phjTextField2.getText());
                                pst.setString(4, emjTextField3.getText());
                                pst.setString(5, injtextfield.getText().toUpperCase());
                                pst.setString(6, tmjTextField5.getText());
                                if(pst.execute()==false)
                                {
                                    if(pst.getUpdateCount()>0)
                                    {
                                        errjLabel5.setText("Record Saved");
                                        jTextField1.setText("");
                                        adjTextField1.setText("");
                                        phjTextField2.setText("");
                                        emjTextField3.setText("");
                                        tmjTextField5.setText("");
                                        injtextfield.setText("");
                                    }
                                }
                            }
                            catch(Exception ex)
                            {
                                System.out.println("error in save"+ex);
                            }
                            cobj.disconnect();
                        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
                       errjLabel5.setText("");
                       jTextField1.setText("");
                      adjTextField1.setText("");
                      phjTextField2.setText("");
                      emjTextField3.setText("");
                      tmjTextField5.setText("");
                      injtextfield.setText("");
                  
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        cobj.connect();
        if(jTextField1.getText().equals(""))
            errjLabel5.setText("Enter City");
        else
            if(adjTextField1.getText().equals(""))
            {
                errjLabel5.setText("Enter Address");
            }
        else
        {
        try
        {
           pst=cobj.con.prepareStatement("select * from tbCenter where City = ? and Address=?");
           pst.setString(2, adjTextField1.getText());
           pst.setString(1, jTextField1.getText());
           rst=pst.executeQuery();
           if(rst.next())
               {
                        errjLabel5.setText("Record found");
                        cid=rst.getLong(1);
                        jTextField1.setText(rst.getString(2).toUpperCase());
                        adjTextField1.setText(rst.getString(3).toUpperCase());
                        phjTextField2.setText(rst.getString(4));
                        emjTextField3.setText(rst.getString(5));
                        injtextfield.setText(rst.getString(6).toUpperCase());
                        tmjTextField5.setText(rst.getString(7));
            }
           else{
               errjLabel5.setText("Record does not exists");
               adjTextField1.setText("");
               phjTextField2.setText("");
               emjTextField3.setText("");
               injtextfield.setText("");
               tmjTextField5.setText("");
           }  
        }
        catch(Exception ex)
        {
            System.out.println("error in search"+ ex);
        }
        cobj.disconnect();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        cobj.connect();
        if(jTextField1.getText().equals(""))
            errjLabel5.setText("Enter City Name");
        else
        if(adjTextField1.getText().equals(""))
            errjLabel5.setText("Enter Address");
        else
            if(phjTextField2.getText().equals(""))
              errjLabel5.setText("Enter Phone  Number");
        else 
            if(emjTextField3.getText().equals(""))
               errjLabel5.setText("Enter Email");
        else
            if(tmjTextField5.getText().equals(""))
               errjLabel5.setText("Enter Timings");
        else
            if(injtextfield.getText().equals(""))
               errjLabel5.setText("Enter Incharge Name");
        else 
                if(phjTextField2.getText().length()!=10)
                            {
                                errjLabel5.setText("Invalid Phone Number");
                            }
        else
            {
                try
                {
                    pst=cobj.con.prepareCall("{call prcupdatecenter(?,?,?,?,?,?,?)}");
                    pst.setLong(1, cid);
                    pst.setString(2, jTextField1.getText().toUpperCase());
                                pst.setString(3, adjTextField1.getText().toUpperCase());
                                pst.setString(4, phjTextField2.getText());
                                pst.setString(5, emjTextField3.getText());
                                pst.setString(6, injtextfield.getText().toUpperCase());
                                pst.setString(7, tmjTextField5.getText());
                                if(pst.execute()==false)
                                {
                                    if(pst.getUpdateCount()>0)
                                    {
                                        errjLabel5.setText("Record updated");
                                        adjTextField1.setText("");
                                        phjTextField2.setText("");
                                        emjTextField3.setText("");
                                        tmjTextField5.setText("");
                                        injtextfield.setText("");
                                    }
                                }
                            }
                            catch(Exception ex)
                            {
                                System.out.println("error in update"+ex);
                            }
                            cobj.disconnect();
                        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        // TODO add your handling code here:
        int key=evt.getKeyCode();
        if(key==10)
            adjTextField1.requestFocus();
        String name=jTextField1.getText();
      
        char c=evt.getKeyChar();
        errjLabel5.setText("");
        if(evt.getKeyChar()>='A' && evt.getKeyChar()<='Z')
        {
            jTextField1.setEditable(true);
        }
        else
       if(evt.getKeyChar()>='a' && evt.getKeyChar()<='z')
        {
            jTextField1.setEditable(true);
            
        }
        
        else
            if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9')
            {
                jTextField1.setEditable(false);
                errjLabel5.setText("Check your City Name");
            }
    }//GEN-LAST:event_jTextField1KeyPressed

    private void adjTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_adjTextField1KeyPressed
        // TODO add your handling code here:
        int key=evt.getKeyCode();
        if(key==10)
            
            phjTextField2.requestFocus();
    }//GEN-LAST:event_adjTextField1KeyPressed

    private void phjTextField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phjTextField2KeyPressed
        // TODO add your handling code here:
        int key=evt.getKeyCode();
        if(key==10)
            emjTextField3.requestFocus();
        
        String ph_num=phjTextField2.getText();
      int length= ph_num.length();
        char c=evt.getKeyChar();
        errjLabel5.setText("");
        if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9'){
        
        if(length<10)
                phjTextField2.setEditable(true);
        
        else
        {
            phjTextField2.setEditable(false);
            errjLabel5.setText("check your Phone Number");
        }
        }
        else
        {
            
            if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE||evt.getExtendedKeyCode()==KeyEvent.VK_ENTER||evt.getExtendedKeyCode()==KeyEvent.VK_DELETE) {      
             phjTextField2.setEditable(true);
             }
            else{
             phjTextField2.setEditable(false);
            errjLabel5.setText("only input numeric values");}}
    }//GEN-LAST:event_phjTextField2KeyPressed

    private void emjTextField3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emjTextField3KeyPressed
        // TODO add your handling code here:
        int key=evt.getKeyCode();
        if(key==10){
            
            injtextfield.requestFocus();}
        
        
        
    }//GEN-LAST:event_emjTextField3KeyPressed

    private void injtextfieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_injtextfieldKeyPressed
        // TODO add your handling code here:
        int key=evt.getKeyCode();
        if(key==10)
            tmjTextField5.requestFocus();
        String name=injtextfield.getText();
      
        char c=evt.getKeyChar();
        errjLabel5.setText("");
        if(evt.getKeyChar()>='A' && evt.getKeyChar()<='Z')
        {
            injtextfield.setEditable(true);
        }
        else
       if(evt.getKeyChar()>='a' && evt.getKeyChar()<='z')
        {
            injtextfield.setEditable(true);
            
        }
        
        else
            if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9')
            {
                injtextfield.setEditable(false);
                errjLabel5.setText("Check your name");
            }
       
    }//GEN-LAST:event_injtextfieldKeyPressed

    private void tmjTextField5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tmjTextField5KeyPressed
        // TODO add your handling code here:
        int key=evt.getKeyCode();
        if(key==10)
           jButton4.requestFocus();
    }//GEN-LAST:event_tmjTextField5KeyPressed

    private void jButton4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton4KeyPressed
        // TODO add your handling code here:
        int key=evt.getKeyCode();
        if(key==39)
            jButton3.requestFocus();
        cobj.connect();
        if(jTextField1.getText().equals(""))
            errjLabel5.setText("Enter City Name");
        else
        if(adjTextField1.getText().equals(""))
            errjLabel5.setText("Enter Address");
        else
            if(phjTextField2.getText().equals(""))
                errjLabel5.setText("Enter Phone  Number");
        else
                if(emjTextField3.getText().equals(""))
                    errjLabel5.setText("Enter Email");
        else
                    if(tmjTextField5.getText().equals(""))
                        errjLabel5.setText("Enter Timings");
        else
                        if(injtextfield.getText().equals(""))
                            errjLabel5.setText("Enter Incharge Name");
        else
                        {
                            
                            try
                            {
                                pst=cobj.con.prepareCall("{call prcinsertcenter(?,?,?,?,?,?)}");
                                pst.setString(1, jTextField1.getText().toUpperCase());
                                pst.setString(2, adjTextField1.getText().toUpperCase());
                                pst.setString(3, phjTextField2.getText());
                                pst.setString(4, emjTextField3.getText());
                                pst.setString(5, injtextfield.getText().toUpperCase());
                                pst.setString(6, tmjTextField5.getText());
                                if(pst.execute()==false)
                                {
                                    if(pst.getUpdateCount()>0)
                                    {
                                        errjLabel5.setText("Record Saved");
                                        adjTextField1.setText("");
                                        phjTextField2.setText("");
                                        emjTextField3.setText("");
                                        tmjTextField5.setText("");
                                        injtextfield.setText("");
                                    }
                                }
                            }
                            catch(Exception ex)
                            {
                                System.out.println("error in save"+ex);
                            }
                            cobj.disconnect();
                        }
    }//GEN-LAST:event_jButton4KeyPressed

    private void jButton3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton3KeyPressed
        // TODO add your handling code here:
        cobj.connect();
        if(jTextField1.getText().equals(""))
            errjLabel5.setText("Enter City");
        else
        {
        try
        {
           pst=cobj.con.prepareStatement("select * from tbCenter where City = ?");
           
           pst.setString(1, jTextField1.getText());
           rst=pst.executeQuery();
           if(rst.next())
               {
                        errjLabel5.setText("Record Found");
                        cid=rst.getLong(1);
                        jTextField1.setText(rst.getString(2).toUpperCase());
                        adjTextField1.setText(rst.getString(3).toUpperCase());
                        phjTextField2.setText(rst.getString(4));
                        emjTextField3.setText(rst.getString(5));
                        injtextfield.setText(rst.getString(6).toUpperCase());
                        tmjTextField5.setText(rst.getString(7));
            }
           else{
               errjLabel5.setText("reocrd does not exists");
               adjTextField1.setText("");
               phjTextField2.setText("");
               emjTextField3.setText("");
               injtextfield.setText("");
               tmjTextField5.setText("");
           } 
        }
        catch(Exception ex)
        {
            System.out.println("error in search"+ ex);
        }
        cobj.disconnect();
        }
    }//GEN-LAST:event_jButton3KeyPressed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        // TODO add your handling code here:
        cobj.connect();
        if(jTextField1.getText().equals(""))
            errjLabel5.setText("Enter City Name");
        else
        if(adjTextField1.getText().equals(""))
            errjLabel5.setText("Enter Address");
        else
            if(phjTextField2.getText().equals(""))
                errjLabel5.setText("Enter Phone  Number");
        else
                if(emjTextField3.getText().equals(""))
                    errjLabel5.setText("Enter Email");
        else
                    if(tmjTextField5.getText().equals(""))
                        errjLabel5.setText("Enter Time ");
        else
                        if(injtextfield.getText().equals(""))
                            errjLabel5.setText("Enter Incharge Name");
        else
                        {
                            
                            try
                            {
                                pst=cobj.con.prepareCall("{call prcupdatecenter(?,?,?,?,?,?)}");
                                pst.setLong(1, cid);
                                pst.setString(2, jTextField1.getText());
                                pst.setString(3, adjTextField1.getText());
                                pst.setString(4, phjTextField2.getText());
                                pst.setString(5, emjTextField3.getText());
                                pst.setString(6, injtextfield.getText());
                                pst.setString(7, tmjTextField5.getText());
                                if(pst.execute()==false)
                                {
                                    if(pst.getUpdateCount()>0)
                                    {
                                        errjLabel5.setText("Record updated");
                                        jTextField1.setText("");
                                        adjTextField1.setText("");
                                        phjTextField2.setText("");
                                        emjTextField3.setText("");
                                        tmjTextField5.setText("");
                                        injtextfield.setText("");
                                    }
                                }
                            }
                            catch(Exception ex)
                            {
                                System.out.println("error in update"+ex);
                            }
                            cobj.disconnect();
                        }
    }//GEN-LAST:event_jButton1KeyPressed

    private void jButton2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton2KeyPressed
        // TODO add your handling code here:
        errjLabel5.setText("");
                       jTextField1.setText("");
                      adjTextField1.setText("");
                      phjTextField2.setText("");
                      emjTextField3.setText("");
                      tmjTextField5.setText("");
                      injtextfield.setText("");
    }//GEN-LAST:event_jButton2KeyPressed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        for(int index=model.getRowCount()-1;index>=0;index--)
             model.removeRow(index);
        if(jTextField2.getText().equals("")){
            jLabel8.setText("Enter City");
            jLabel9.setText("Nothing is searched");
        }
        else
        {
            int i=0;
            cobj.connect();
            try
            {
               pst=cobj.con.prepareStatement("select * from tbCenter where City=?");
               
               pst.setString(1,jTextField2.getText());
               
               rst=pst.executeQuery();
               while(rst.next())
               {
                   model.insertRow(model.getRowCount(), new Object[]{rst.getString(1),rst.getString(2),rst.getString(3),rst.getString(4),rst.getString(5),rst.getString(6),rst.getString(7)});
                   i++;
               }
                jLabel9.setText("Number of Center "+i);
            }
            catch(Exception ex)
            {
                System.out.println("error in search"+ex);
            }
            cobj.disconnect();
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyPressed
        // TODO add your handling code here:
        String name=jTextField2.getText();
      
        char c=evt.getKeyChar();
        errjLabel5.setText("");
        if(evt.getKeyChar()>='A' && evt.getKeyChar()<='Z')
        {
            jTextField2.setEditable(true);
        }
        else
       if(evt.getKeyChar()>='a' && evt.getKeyChar()<='z')
        {
            jTextField2.setEditable(true);
            
        }
        
        else
            if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9')
            {
                jTextField2.setEditable(false);
                jLabel9.setText("Check your City Name");
            }
    }//GEN-LAST:event_jTextField2KeyPressed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        cobj.connect();
         for(int index=model.getRowCount()-1;index>=0;index--)
             model.removeRow(index);
        int j=0;
        try
        {
            pst=cobj.con.prepareStatement("select * from tbCenter");
            rst=pst.executeQuery();
            while(rst.next()){
                model.insertRow(model.getRowCount(), new Object[]{rst.getString(1),rst.getString(2),rst.getString(3),rst.getString(4),rst.getString(5),rst.getString(6),rst.getString(7)});
                j++;
            }
            jLabel9.setText("Total Number of Center "+j);
        }
        catch(Exception ex)
        {
            System.out.println("error in table");
        }
        cobj.disconnect();
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Center.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Center.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Center.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Center.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Center().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adjTextField1;
    private javax.swing.JTextField emjTextField3;
    private javax.swing.JLabel errjLabel5;
    private javax.swing.JTextField injtextfield;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField phjTextField2;
    private javax.swing.JTextField tmjTextField5;
    // End of variables declaration//GEN-END:variables

}
