/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cvcm;

import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/**
 *
 * @author Anshul
 */
public class ChangePassword extends javax.swing.JFrame {
ConnectionClass cobj=new ConnectionClass();
    PreparedStatement pst;
    ResultSet rst;
    boolean symbole,uppercase,lowercase,digit;
   
    /**
     * Creates new form ChangePassword
     */
    public ChangePassword() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        newjPasswordField1 = new javax.swing.JPasswordField();
        opwjPasswordField2 = new javax.swing.JPasswordField();
        cpwjPasswordField3 = new javax.swing.JPasswordField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        errjLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cvcm/resources/resources/Security-Password-2-icon.png"))); // NOI18N
        jLabel1.setText("Old Password");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cvcm/resources/resources/Security-Password-2-icon.png"))); // NOI18N
        jLabel2.setText("New Password");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cvcm/resources/resources/Security-Password-2-icon.png"))); // NOI18N
        jLabel3.setText("Confirm New Password");

        newjPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newjPasswordField1ActionPerformed(evt);
            }
        });
        newjPasswordField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                newjPasswordField1KeyPressed(evt);
            }
        });

        opwjPasswordField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                opwjPasswordField2KeyPressed(evt);
            }
        });

        cpwjPasswordField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cpwjPasswordField3KeyPressed(evt);
            }
        });

        jCheckBox1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBox1.setText("SHOW");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jCheckBox2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBox2.setText("SHOW");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });

        jCheckBox3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBox3.setText("SHOW");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });

        errjLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("Change Password");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cvcm/resources/resources/Users-Name-icon (1).png"))); // NOI18N
        jLabel4.setText("UserName");

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(errjLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 241, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(opwjPasswordField2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cpwjPasswordField3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(newjPasswordField1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox1)
                            .addComponent(jCheckBox3)
                            .addComponent(jCheckBox2))
                        .addGap(12, 12, 12))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(opwjPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox1))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newjPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jCheckBox2)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cpwjPasswordField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox3))
                .addGap(28, 28, 28)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(errjLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here
        if(jCheckBox2.isSelected())
            newjPasswordField1.setEchoChar((char)0);
        else
            newjPasswordField1.setEchoChar('*');
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void newjPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newjPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newjPasswordField1ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        if(jCheckBox1.isSelected())
            opwjPasswordField2.setEchoChar((char)0);
        else
            opwjPasswordField2.setEchoChar('*');
        
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        // TODO add your handling code here:
        if(jCheckBox3.isSelected())
            cpwjPasswordField3.setEchoChar((char)0);
        else
            cpwjPasswordField3.setEchoChar('*');
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here
        
        if(jTextField1.getText().equals(""))
            errjLabel4.setText("Enter Username");
        else
        if(opwjPasswordField2.getText().equals(""))
            errjLabel4.setText("Enter Old Password");
        else
            if(newjPasswordField1.getText().equals(""))
                errjLabel4.setText("Enter New Password");
            else
                if(uppercase==false||lowercase==false||symbole==false||digit==false)
                {
                errjLabel4.setText("Password Format Incoorect");
                }
                    else
                    if(newjPasswordField1.getText().length()<8)
                        errjLabel4.setText("Password Format Incoorect");
                else{
                    
                    cobj.connect();
                    try
                    {
                        pst=cobj.con.prepareStatement("update tbLogin set Password= ? where UserName=? and Password=?");
                        pst.setString(1, newjPasswordField1.getText());
                        pst.setString(2, jTextField1.getText());
                        pst.setString(3, opwjPasswordField2.getText());
                        
                    
                        if(pst.execute()==false)
                        if(pst.getUpdateCount()>0){
                            PasswordChanged pc=new PasswordChanged();
                            pc.setVisible(true);
                            this.dispose();
                            jTextField1.setText("");
                            opwjPasswordField2.setText("");
                            newjPasswordField1.setText("");
                            cpwjPasswordField3.setText("");
                        }
                                
                   }
                    catch(Exception ex)
                    {
                        System.out.println("error in change password"+ex);
                    }
                    cobj.disconnect();
                }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        // TODO add your handling code here:
        int key=evt.getKeyCode();
        if(key==10)
            opwjPasswordField2.requestFocus();
    }//GEN-LAST:event_jTextField1KeyPressed

    private void opwjPasswordField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_opwjPasswordField2KeyPressed
        // TODO add your handling code here:
        int key=evt.getKeyCode();
        if(key==10)
            newjPasswordField1.requestFocus();
    }//GEN-LAST:event_opwjPasswordField2KeyPressed

    private void newjPasswordField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_newjPasswordField1KeyPressed
        // TODO add your handling code here:
        int key=evt.getKeyCode();
        if(key==10)
            cpwjPasswordField3.requestFocus();
        
        String name=newjPasswordField1.getText();
      
        char c=evt.getKeyChar();
        errjLabel4.setText("");
        
        if(evt.getKeyChar()>='A' && evt.getKeyChar()<='Z')
        {
          newjPasswordField1.setEditable(true);
          uppercase=true;
       }
        else
        if(evt.getKeyChar()>='a' && evt.getKeyChar()<='z')
        {
            newjPasswordField1.setEditable(true);
            lowercase=true;
        }
        
        else
            if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9')
            {
                newjPasswordField1.setEditable(true);
                digit=true;
            }
       else
             if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE||evt.getExtendedKeyCode()==KeyEvent.VK_DELETE||evt.getExtendedKeyCode()==KeyEvent.VK_CAPS_LOCK||evt.getExtendedKeyCode()==KeyEvent.VK_SHIFT||evt.getExtendedKeyCode()==KeyEvent.VK_ENTER) 
             {
             newjPasswordField1.setEditable(true);
             
             }
             else
                 if(evt.getExtendedKeyCode()==KeyEvent.VK_DOLLAR)
                 {
                newjPasswordField1.setEditable(true);
                symbole=true;
                  
                 }
        else
                     errjLabel4.setText("Password Pattern Invalid");
    }//GEN-LAST:event_newjPasswordField1KeyPressed

    private void cpwjPasswordField3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cpwjPasswordField3KeyPressed
        // TODO add your handling code here:
        int key=evt.getKeyCode();
        if(key==10)
            jButton1.requestFocus();
    }//GEN-LAST:event_cpwjPasswordField3KeyPressed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        // TODO add your handling code here:
        if(jTextField1.getText().equals(""))
            errjLabel4.setText("enter username");
        else
        if(opwjPasswordField2.getText().equals(""))
            errjLabel4.setText("Enter Old Password");
        else
            if(newjPasswordField1.getText().equals(""))
                errjLabel4.setText("Enter New Password");
        else
                
                {
                    
                    cobj.connect();
                    try
                    {
                        pst=cobj.con.prepareStatement("update tbLogin set Password= ? where UserName=? and Password=?");
                        pst.setString(1, newjPasswordField1.getText());
                        pst.setString(2, jTextField1.getText());
                        pst.setString(3, opwjPasswordField2.getText());
                        
                    
                        if(pst.execute()==false)
                        if(pst.getUpdateCount()>0)
                        {
                            PasswordChanged pc=new PasswordChanged();
                            pc.setVisible(true);
                            jTextField1.setText("");
                            opwjPasswordField2.setText("");
                            newjPasswordField1.setText("");
                            cpwjPasswordField3.setText("");
                            this.setVisible(false);
                        }
                                
                   }
                    catch(Exception ex)
                    {
                        System.out.println("error in change password"+ex);
                    }
                    cobj.disconnect();
                }
    }//GEN-LAST:event_jButton1KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangePassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField cpwjPasswordField3;
    private javax.swing.JLabel errjLabel4;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPasswordField newjPasswordField1;
    private javax.swing.JPasswordField opwjPasswordField2;
    // End of variables declaration//GEN-END:variables
}
