/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cvcm;

import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 *
 * @author Anshul
 */
public class Citizen extends javax.swing.JFrame {
ConnectionClass cobj=new ConnectionClass();
    PreparedStatement pst;
    ResultSet rst;
    String radiotext="";
    long cid;
 
    /**
     * Creates new form Citizen
     * 
     */
    public Citizen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton5 = new javax.swing.JButton();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        errjLabel10 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        phnjTextField1 = new javax.swing.JTextField();
        emjTextField2 = new javax.swing.JTextField();
        dorjTextField3 = new javax.swing.JTextField();
        adhrjTextField4 = new javax.swing.JTextField();
        namejTextField5 = new javax.swing.JTextField();
        fnamejTextField6 = new javax.swing.JTextField();
        adjTextField7 = new javax.swing.JTextField();
        agejTextField8 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        jButton5.setText("jButton5");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Name");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Father's Name");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Address");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Age");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Gender");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Phone Number");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Email");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Aadhar Number");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Date Of Registration");

        errjLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Male");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Others");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Female");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        jRadioButton3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jRadioButton3KeyPressed(evt);
            }
        });

        phnjTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                phnjTextField1KeyPressed(evt);
            }
        });

        emjTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emjTextField2ActionPerformed(evt);
            }
        });
        emjTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                emjTextField2KeyPressed(evt);
            }
        });

        adhrjTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adhrjTextField4ActionPerformed(evt);
            }
        });
        adhrjTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                adhrjTextField4KeyPressed(evt);
            }
        });

        namejTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namejTextField5ActionPerformed(evt);
            }
        });
        namejTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                namejTextField5KeyPressed(evt);
            }
        });

        fnamejTextField6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fnamejTextField6KeyPressed(evt);
            }
        });

        adjTextField7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                adjTextField7KeyPressed(evt);
            }
        });

        agejTextField8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                agejTextField8KeyPressed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setText("Search");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton4.setText("Update");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(123, 123, 123)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(adhrjTextField4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dorjTextField3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(phnjTextField1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(namejTextField5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fnamejTextField6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(adjTextField7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(agejTextField8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButton1)
                                .addGap(30, 30, 30)
                                .addComponent(jRadioButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jRadioButton2))
                            .addComponent(emjTextField2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 44, Short.MAX_VALUE)))
                .addGap(50, 50, 50))
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(errjLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(namejTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(fnamejTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(adjTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(agejTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(phnjTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(emjTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(dorjTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(adhrjTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton2)
                    .addComponent(jButton1)
                    .addComponent(jButton4))
                .addGap(37, 37, 37)
                .addComponent(errjLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adhrjTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adhrjTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adhrjTextField4ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        if(jRadioButton1.isSelected())
        {
            jRadioButton2.setSelected(false);
            jRadioButton3.setSelected(false);
            radiotext="Male";
        }
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int value=18;
        if(namejTextField5.getText().equals(""))
            errjLabel10.setText("enter name");
        else
            if(fnamejTextField6.getText().equals(""))
                errjLabel10.setText("enter father name");
            
        else
             if(adjTextField7.getText().equals(""))
                 errjLabel10.setText("enter address");
             else 
            if(phnjTextField1.getText().equals(""))
                     errjLabel10.setText("enter phone number");
        else
              
                 if(agejTextField8.getText().equals(""))
                     errjLabel10.setText("enter age");
        else
              if(dorjTextField3.getText().equals(""))
                      errjLabel10.setText("enter date");
        else
                  if(adhrjTextField4.getText().equals(""))
                      errjLabel10.setText("adhar card number");
        else
                      if(phnjTextField1.getText().length()!=10)
                      {
                          errjLabel10.setText("Invlid phone number");
                      }
        else
                          if(agejTextField8.getText().length()!=2)
                      {
                          errjLabel10.setText("Age group not allowed");
                      }
        else
                              if(adhrjTextField4.getText().length()!=12)
                      {
                          errjLabel10.setText("Invlid adhar number");
                      }
        else 
           {
                      cobj.connect();
                      try
                      {
                          pst=cobj.con.prepareCall("{call prcinsertcitizen(?,?,?,?,?,?,?,?,?)}");
                          pst.setString(1, namejTextField5.getText().toUpperCase());
                          pst.setString(2, fnamejTextField6.getText().toUpperCase());
                          pst.setString(3, adjTextField7.getText());
                          pst.setString(4, agejTextField8.getText());
                          pst.setString(5, radiotext.toUpperCase());
                          pst.setString(6, phnjTextField1.getText());
                          pst.setString(7, emjTextField2.getText());
                          pst.setString(8, dorjTextField3.getText());
                          pst.setString(9, adhrjTextField4.getText());
                          if(pst.execute()==false)
                          
                              if(pst.getUpdateCount()>0)
                              {
                                  errjLabel10.setText("Record save");
                                  namejTextField5.setText("");
                                  fnamejTextField6.setText("");
                                  adjTextField7.setText("");
                                  agejTextField8.setText("");
                                  phnjTextField1.setText("");
                                  emjTextField2.setText("");
                                  dorjTextField3.setText("");
                                  adhrjTextField4.setText("");
                              }
                          
                      }
                      catch(Exception ex)
                      {
                          System.out.print("error in save"+ex);
                      }
                      cobj.disconnect();
                  }
                      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(namejTextField5.getText().equals(""))
            errjLabel10.setText("Enter Name");
        else
            if(phnjTextField1.getText().equals(""))
                errjLabel10.setText("Enter Phone Number");
        else
            {
                cobj.connect();
                try
                {
                    pst=cobj.con.prepareStatement("select* from tbCitizen where Name=? and Phone=?");
                    pst.setString(1, namejTextField5.getText());
                    pst.setString(2, phnjTextField1.getText());
                    rst=pst.executeQuery();
                    if(rst.next()==true)
                    {
                        errjLabel10.setText("Record Found");
                        cid=rst.getLong(1);
                        System.out.println(cid);
                        namejTextField5.setText(rst.getString(2).toUpperCase());
                        fnamejTextField6.setText(rst.getString(3).toUpperCase());
                        adjTextField7.setText(rst.getString(4));
                        agejTextField8.setText(rst.getString(5));
                        if(rst.getString(6).equals("male"))
                            jRadioButton1.setSelected(true);
                        else
                            if(rst.getString(6).equals("female"))
                                jRadioButton3.setSelected(true);
                        else
                                if(rst.getString(6).equals("Others"))
                                    jRadioButton2.setSelected(true);
                        phnjTextField1.setText(rst.getString(7));
                        emjTextField2.setText(rst.getString(8));
                        dorjTextField3.setText(rst.getString(9));
                        adhrjTextField4.setText(rst.getString(10));
                    }
                    else
                    {
                        errjLabel10.setText("Record does not Exists");
                    
                        fnamejTextField6.setText("");
                        adjTextField7.setText("");
                        agejTextField8.setText("");
                        emjTextField2.setText("");
                        dorjTextField3.setText("");
                        adhrjTextField4.setText("");
                    }
                }
                catch(Exception ex)
                {
                    System.out.println("error in search"+ex);
                }
                cobj.disconnect();
            }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
       if(jRadioButton3.isSelected())
        {
            jRadioButton2.setSelected(false);
            jRadioButton1.setSelected(false);
            radiotext="female";
        } 
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        if(jRadioButton2.isSelected())
        {
            jRadioButton1.setSelected(false);
            jRadioButton3.setSelected(false);
            radiotext="other";
        }
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void namejTextField5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_namejTextField5KeyPressed
        // TODO add your handling code here:
        int key=evt.getKeyCode();
        if(key==10)
            fnamejTextField6.requestFocus();
         String name=namejTextField5.getText();
      
        char c=evt.getKeyChar();
        errjLabel10.setText("");
        if(evt.getKeyChar()>='A' && evt.getKeyChar()<='Z')
        {
            namejTextField5.setEditable(true);
        }
        else
       if(evt.getKeyChar()>='a' && evt.getKeyChar()<='z')
        {
            namejTextField5.setEditable(true);
            
        }
        
        else
            if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9')
            {
                namejTextField5.setEditable(false);
                
                errjLabel10.setText("Check your Name");
            }
        else
                if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE||evt.getExtendedKeyCode()==KeyEvent.VK_DELETE||
                        evt.getExtendedKeyCode()==KeyEvent.VK_ENTER)
                {
                    namejTextField5.setEditable(true);
                }
       
        
                
    }//GEN-LAST:event_namejTextField5KeyPressed

    private void fnamejTextField6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fnamejTextField6KeyPressed
        // TODO add your handling code here:
        int key=evt.getKeyCode();
        if(key==10)
            adjTextField7.requestFocus();
        
        String name=fnamejTextField6.getText();
      
        char c=evt.getKeyChar();
        errjLabel10.setText("");
        if(evt.getKeyChar()>='A' && evt.getKeyChar()<='Z')
        {
         fnamejTextField6.setEditable(true);
        }
        else
        if(evt.getKeyChar()>='a' && evt.getKeyChar()<='z')
        {
            fnamejTextField6.setEditable(true);
           
        }
       else
       if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9')
            {
                fnamejTextField6.setEditable(false);
                 errjLabel10.setText("check your Father's Name");
            }
        if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE||evt.getExtendedKeyCode()==KeyEvent.VK_DELETE||
                        evt.getExtendedKeyCode()==KeyEvent.VK_ENTER)
                {
                    fnamejTextField6.setEditable(true);
                }
    }//GEN-LAST:event_fnamejTextField6KeyPressed

    private void adjTextField7KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_adjTextField7KeyPressed
        // TODO add your handling code here:
        int key=evt.getKeyCode();
        if(key==10)
            agejTextField8.requestFocus();
    }//GEN-LAST:event_adjTextField7KeyPressed

    private void agejTextField8KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_agejTextField8KeyPressed
        // TODO add your handling code here:
        int key=evt.getKeyCode();
        if(key==10)
            jRadioButton1.requestFocus();
        String ph_num=agejTextField8.getText();
      int length= ph_num.length();
        char c=evt.getKeyChar();
        errjLabel10.setText("");
        if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9'){
        
        if(length<3)
                agejTextField8.setEditable(true);
        
        else
        {
            agejTextField8.setEditable(false);
            errjLabel10.setText("check your Age");
        }
        }
        else
        {
            
         
            if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE||evt.getExtendedKeyCode()==KeyEvent.VK_DELETE||evt.getExtendedKeyCode()==KeyEvent.VK_ENTER) {      
             agejTextField8.setEditable(true);
             }
        else
            {
                agejTextField8.setEditable(false);
                    errjLabel10.setText("Check your Age");}}
       
    }//GEN-LAST:event_agejTextField8KeyPressed

    private void jRadioButton3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jRadioButton3KeyPressed
        // TODO add your handling code here:
        
            
    }//GEN-LAST:event_jRadioButton3KeyPressed

    private void namejTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namejTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namejTextField5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if(namejTextField5.getText().equals(""))
            errjLabel10.setText("enter name");
        else
            if(fnamejTextField6.getText().equals(""))
                errjLabel10.setText("enter father name");
        else
             if(adjTextField7.getText().equals(""))
                 errjLabel10.setText("enter address");
             else 
            if(phnjTextField1.getText().equals(""))
                     errjLabel10.setText("enter phone number");
        else
              
                 if(agejTextField8.getText().equals(""))
                     errjLabel10.setText("enter age");
        else
              if(dorjTextField3.getText().equals(""))
                      errjLabel10.setText("enter date");
        else
                  if(adhrjTextField4.getText().equals(""))
                      errjLabel10.setText("adhar card number");
        else
                       if(phnjTextField1.getText().length()!=10)
                      {
                          errjLabel10.setText("Invlid phone number");
                      }
        else
                          if(agejTextField8.getText().length()!=2)
                      {
                          errjLabel10.setText("Age group not allowed");
                      }
        else
                              if(adhrjTextField4.getText().length()!=12)
                      {
                          errjLabel10.setText("Invlid adhar number");
                      }
        else 
                             
        
       
                 
                         {
                      cobj.connect();
                      try
                      {
                          if(jRadioButton1.isSelected())
        {
            
            radiotext="male";
        }
                          else
                              if(jRadioButton2.isSelected())
                              {
                                  radiotext="others";
                              }
                          else
                                  if(jRadioButton3.isSelected())
                                  {
                                      radiotext="female";
                                  }
                          pst=cobj.con.prepareCall("{call prcupdatecitizen(?,?,?,?,?,?,?,?,?,?)}");
                          pst.setLong(1, cid);
                          pst.setString(2, namejTextField5.getText().toUpperCase());
                          pst.setString(3, fnamejTextField6.getText().toUpperCase());
                          pst.setString(4, adjTextField7.getText());
                          pst.setString(5, agejTextField8.getText());
                          
                          pst.setString(6, radiotext);
                          pst.setString(7, phnjTextField1.getText());
                          pst.setString(8, emjTextField2.getText());
                          pst.setString(9, dorjTextField3.getText());
                          pst.setString(10, adhrjTextField4.getText());
                          if(pst.execute()==false)
                          
                              if(pst.getUpdateCount()>0)
                              {
                                  errjLabel10.setText("Record Updated");
                                  namejTextField5.setText("");
                                  fnamejTextField6.setText("");
                                  adjTextField7.setText("");
                                  agejTextField8.setText("");
                                  phnjTextField1.setText("");
                                  emjTextField2.setText("");
                                  dorjTextField3.setText("");
                                  adhrjTextField4.setText("");
                              }
                          
                      }
                      catch(Exception ex)
                      {
                          System.out.print("error in update"+ex);
                      }
                      cobj.disconnect();
    }//GEN-LAST:event_jButton4ActionPerformed
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
                    errjLabel10.setText("");
                    namejTextField5.setText("");
                    fnamejTextField6.setText("");
                    adjTextField7.setText("");
                    phnjTextField1.setText("");
                    agejTextField8.setText("");
                    emjTextField2.setText("");
                    dorjTextField3.setText("");
                    adhrjTextField4.setText("");
                    
                    
                
    }//GEN-LAST:event_jButton2ActionPerformed

    private void phnjTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phnjTextField1KeyPressed
        // TODO add your handling code here:
      String ph_num=phnjTextField1.getText();
      int length= ph_num.length();
        char c=evt.getKeyChar();
        errjLabel10.setText("");
        if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9'){
        
        if(length<10)
                phnjTextField1.setEditable(true);
        
        else
        {
            phnjTextField1.setEditable(false);
            errjLabel10.setText("check your Number");
        }
        }
        else
        {
        
         if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE||evt.getExtendedKeyCode()==KeyEvent.VK_DELETE||evt.getExtendedKeyCode()==KeyEvent.VK_ENTER) {      
             phnjTextField1.setEditable(true);
             
             }
        else
         {
             phnjTextField1.setEditable(false);
            
           errjLabel10.setText("Only Input Numeric Values");
        }
        }
    }//GEN-LAST:event_phnjTextField1KeyPressed

    private void adhrjTextField4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_adhrjTextField4KeyPressed
        // TODO add your handling code here:
        String ph_num=adhrjTextField4.getText();
      int length= ph_num.length();
        char c=evt.getKeyChar();
        errjLabel10.setText("");
        if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9'){
        
        if(length<12)
                adhrjTextField4.setEditable(true);
        
        else
        {
            adhrjTextField4.setEditable(false);
            errjLabel10.setText("check your  AAdhar number");
        }
        }
        else
        {
            
         if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE||evt.getExtendedKeyCode()==KeyEvent.VK_DELETE)     
             adhrjTextField4.setEditable(true);
             
        else
         {
             adhrjTextField4.setEditable(false);
             errjLabel10.setText("check your Aadhar Number1");
         
         }      }
    }//GEN-LAST:event_adhrjTextField4KeyPressed

    private void emjTextField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emjTextField2KeyPressed
        // TODO add your handling code here:
         
    }//GEN-LAST:event_emjTextField2KeyPressed

    private void emjTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emjTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emjTextField2ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Citizen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Citizen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Citizen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Citizen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Citizen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adhrjTextField4;
    private javax.swing.JTextField adjTextField7;
    private javax.swing.JTextField agejTextField8;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTextField dorjTextField3;
    private javax.swing.JTextField emjTextField2;
    private javax.swing.JLabel errjLabel10;
    private javax.swing.JTextField fnamejTextField6;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JTextField namejTextField5;
    private javax.swing.JTextField phnjTextField1;
    // End of variables declaration//GEN-END:variables
}
