/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cvcm;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Date;

/**
 *
 * @author Anshul
 */
public class Feedback extends javax.swing.JFrame {
ConnectionClass cobj=new ConnectionClass();
    PreparedStatement pst;
    ResultSet rst;
    int index=0;
    long cid[]=new long[100],fid;
    Date date=new Date();
    /**
     * Creates new form Feedback
     */
    public Feedback() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        errjLabel6 = new javax.swing.JLabel();
        dofjTextField1 = new javax.swing.JTextField();
        adjTextField2 = new javax.swing.JTextField();
        rejTextField3 = new javax.swing.JTextField();
        sjTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Aadhar Number/CitizenId");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Date Of Feedback");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Action Details");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Remarks");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Status");

        errjLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        rejTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rejTextField3ActionPerformed(evt);
            }
        });

        sjTextField4.setEditable(false);
        sjTextField4.setText("Pending");
        sjTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sjTextField4ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("Reset");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setText("Save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setText("Search");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton4.setText("Update");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(64, 64, 64)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(adjTextField2)
                                    .addComponent(dofjTextField1)
                                    .addComponent(jTextField1)
                                    .addComponent(rejTextField3)
                                    .addComponent(sjTextField4, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addComponent(errjLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(60, 60, 60))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(45, 45, 45)
                        .addComponent(jButton3)
                        .addGap(53, 53, 53)
                        .addComponent(jButton4)
                        .addGap(46, 46, 46)
                        .addComponent(jButton1)
                        .addContainerGap(12, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(dofjTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(adjTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(rejTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(sjTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton1)
                    .addComponent(jButton3)
                    .addComponent(jButton2))
                .addGap(44, 44, 44)
                .addComponent(errjLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rejTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rejTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rejTextField3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(dofjTextField1.getText().equals(""))
            errjLabel6.setText("Enter Date of Feedbcak");
        else
            if(adjTextField2.getText().equals(""))
                errjLabel6.setText("enter action details");
        else
                if(rejTextField3.getText().equals(""))
                    errjLabel6.setText("enter remarks");
        else
                    if(jTextField1.getText().equals(""))
                        errjLabel6.setText("Enter AAdhar Card Number");
                    else 
                {
                        
                    cobj.connect();
                    try
                    {
                      pst=cobj.con.prepareCall("{call prcinsertfeedback(?,?,?,?,?)}");
                      pst.setString(1, jTextField1.getText());
                      pst.setString(2, dofjTextField1.getText());
                      pst.setString(3,adjTextField2.getText() );
                      pst.setString(4, rejTextField3.getText());
                      pst.setString(5, sjTextField4.getText());
                      if(pst.execute()==false)
                          if(pst.getUpdateCount()>0)
                          {
                              errjLabel6.setText("record save");
                              dofjTextField1.setText("");
                              adjTextField2.setText("");
                              rejTextField3.setText("");
                              sjTextField4.setText("");
                              jTextField1.setText("");
                              
                          }
                    }
                    catch(Exception ex)
                    {
                        System.out.println("error in save"+ex);
               }
                    cobj.disconnect();
                }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        errjLabel6.setText("");
        dofjTextField1.setText("");
        adjTextField2.setText("");
        rejTextField3.setText("");
        sjTextField4.setText("");
        jTextField1.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         if(dofjTextField1.getText().equals(""))
            errjLabel6.setText("Enter Date of Feedback");
        else
            if(adjTextField2.getText().equals(""))
                errjLabel6.setText("enter action details");
        else
                if(rejTextField3.getText().equals(""))
                    errjLabel6.setText("enter remarks");
        else
                {
                    cobj.connect();
                    try
                    {
                      pst=cobj.con.prepareCall("{call prcupdatefeedback(?,?,?,?,?,?)}");
                      pst.setLong(1, fid);
                      pst.setString(2, jTextField1.getText());
                      pst.setString(3, dofjTextField1.getText());
                      pst.setString(4,adjTextField2.getText() );
                      pst.setString(5, rejTextField3.getText());
                      pst.setString(6, sjTextField4.getText());
                      if(pst.execute()==false)
                          if(pst.getUpdateCount()>0)
                          {
                              errjLabel6.setText("record update");
                              dofjTextField1.setText("");
                              adjTextField2.setText("");
                              rejTextField3.setText("");
                              sjTextField4.setText("");
                              jTextField1.setText("");
                          }
                    }
                    catch(Exception ex)
                    {
                        System.out.println("error in update"+ex);
               }
                    cobj.disconnect();
                }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
           cobj.connect();
           
           
                    try
                    {
                      pst=cobj.con.prepareStatement("select * from tbFeedback where CitizenId=? ");
                      pst.setString(1, jTextField1.getText());
                      rst=pst.executeQuery();
                      if(rst.next())
                       {
                              errjLabel6.setText("record found");
                              fid=rst.getLong(1);
                              jTextField1.setText(rst.getString(2));
                              dofjTextField1.setText(rst.getString(3));
                              adjTextField2.setText(rst.getString(4));
                              rejTextField3.setText(rst.getString(5));
                              sjTextField4.setText(rst.getString(6));
                              sjTextField4.setEditable(true);
                          }
                    }
                    catch(Exception ex)
                    {
                        System.out.println("error in search"+ex);
               }
                    cobj.disconnect();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void sjTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sjTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sjTextField4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Feedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Feedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Feedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Feedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Feedback().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adjTextField2;
    private javax.swing.JTextField dofjTextField1;
    private javax.swing.JLabel errjLabel6;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField rejTextField3;
    private javax.swing.JTextField sjTextField4;
    // End of variables declaration//GEN-END:variables
}
