/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cvcm;

import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/**
 *
 * @author Anshul
 */
public class Medicine extends javax.swing.JFrame {
ConnectionClass cobj=new ConnectionClass();
    PreparedStatement pst;
    ResultSet rst;
    long mid;
    /**
     * Creates new form Medicine
     */
    public Medicine() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        errjLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        mnamejTextField1 = new javax.swing.JTextField();
        dijTextField2 = new javax.swing.JTextField();
        dejTextField3 = new javax.swing.JTextField();
        qtyjTextField4 = new javax.swing.JTextField();
        cnamejTextField5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Medicine Name");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Comapny Name");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Date of Issue");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Date of Expiry");

        errjLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Quantity");

        mnamejTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                mnamejTextField1KeyPressed(evt);
            }
        });

        dijTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dijTextField2ActionPerformed(evt);
            }
        });
        dijTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dijTextField2KeyPressed(evt);
            }
        });

        dejTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dejTextField3ActionPerformed(evt);
            }
        });
        dejTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dejTextField3KeyPressed(evt);
            }
        });

        qtyjTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtyjTextField4ActionPerformed(evt);
            }
        });
        qtyjTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                qtyjTextField4KeyPressed(evt);
            }
        });

        cnamejTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cnamejTextField5KeyPressed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setText("Reset");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton4.setText("Search");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(mnamejTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cnamejTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(qtyjTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dejTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dijTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2)
                                .addGap(10, 10, 10)
                                .addComponent(jButton3))))
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(errjLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(mnamejTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cnamejTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(dijTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(dejTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(qtyjTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton4)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(34, 34, 34)
                .addComponent(errjLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dijTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dijTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dijTextField2ActionPerformed

    private void qtyjTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtyjTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qtyjTextField4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        errjLabel5.setText("");
        mnamejTextField1.setText("");
        cnamejTextField5.setText("");
        qtyjTextField4.setText("");
        dejTextField3.setText("");
        dijTextField2.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(mnamejTextField1.getText().equals(""))
            errjLabel5.setText("Enter medicine Name");
        else
            if(cnamejTextField5.getText().equals(""))
            errjLabel5.setText("Enter company Name");
        else
                if(dijTextField2.getText().equals(""))
            errjLabel5.setText("Enter Date of issue ");
        else
                    if(dejTextField3.getText().equals(""))
            errjLabel5.setText("Enter  Expiray Date");
        else
                        if(qtyjTextField4.getText().equals(""))
            errjLabel5.setText("Enter Medicine quantity");
        else
                        {
                            cobj.connect();
                            try
                            {
                              pst=cobj.con.prepareCall("{call prcinsertmedicine(?,?,?,?,?)}");
                              pst.setString(1, mnamejTextField1.getText().toUpperCase());
                              pst.setString(2, cnamejTextField5.getText().toUpperCase());
                              pst.setString(3, dijTextField2.getText());
                              pst.setString(4, dejTextField3.getText());
                              pst.setString(5, qtyjTextField4.getText());
                              if(pst.execute()==false)
                              {
                                  if(pst.getUpdateCount()>0)
                                      errjLabel5.setText("record save");
                                      mnamejTextField1.setText("");
                                      cnamejTextField5.setText("");
                                      dijTextField2.setText("");
                                      dejTextField3.setText("");
                                      qtyjTextField4.setText("");
                              }
                            }
                            catch(Exception ex)
                            {
                                System.out.println("error in save"+ex);   
                            }
                            cobj.disconnect();
                        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(mnamejTextField1.getText().equals(""))
            errjLabel5.setText("Enter medicine name");
        else
            if(cnamejTextField5.getText().equals(""))
            errjLabel5.setText("Enter company name");
        else
                if(dijTextField2.getText().equals(""))
            errjLabel5.setText("Enter date of issue ");
        else
                    if(dejTextField3.getText().equals(""))
            errjLabel5.setText("Enter date of ecpiray");
        else
                        if(qtyjTextField4.getText().equals(""))
            errjLabel5.setText("Enter medicine quantity");
        else
                        {
                            cobj.connect();
                            try
                            {
                              pst=cobj.con.prepareCall("{call prcupdatemedicine(?,?,?,?,?,?)}");
                              pst.setLong(1, mid);
                              pst.setString(2, mnamejTextField1.getText().toUpperCase());
                              pst.setString(3, cnamejTextField5.getText().toUpperCase());
                              pst.setString(4, dijTextField2.getText());
                              pst.setString(5, dejTextField3.getText());
                              pst.setString(6, qtyjTextField4.getText());
                              if(pst.execute()==false)
                              {
                                  if(pst.getUpdateCount()>0)
                                      errjLabel5.setText("record update");
                                      mnamejTextField1.setText("");
                                      cnamejTextField5.setText("");
                                      dijTextField2.setText("");
                                      dejTextField3.setText("");
                                      qtyjTextField4.setText("");
                              }
                            }
                            catch(Exception ex)
                            {
                                System.out.println("error in update"+ex);   
                            }
                            cobj.disconnect();
                        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if(mnamejTextField1.getText().equals(""))
            errjLabel5.setText("Enter Medicine Name");
        else
            if(cnamejTextField5.getText().equals(""))
            errjLabel5.setText("Enter Company Name");
        else
                
                        {
                            cobj.connect();
                            try
                            {
                              pst=cobj.con.prepareStatement("select * from tbMedicine where MedicineName=? and CompanyName=?");
                              
                              pst.setString(1, mnamejTextField1.getText());
                              pst.setString(2, cnamejTextField5.getText());
                              rst=pst.executeQuery();
                             
                              if(rst.next())
                              {
                                      errjLabel5.setText("record found");
                                      mid=rst.getLong(1);
                                      mnamejTextField1.setText(rst.getString(2).toUpperCase());
                                      cnamejTextField5.setText(rst.getString(3).toUpperCase());
                                      dijTextField2.setText(rst.getString(4));
                                      dejTextField3.setText(rst.getString(5));
                                      qtyjTextField4.setText(rst.getString(6));
                              }
                              else
                              {
                                  errjLabel5.setText("record does not exists");
                              }
                            }
                            catch(Exception ex)
                            {
                                System.out.println("error in search"+ex);   
                            }
                            cobj.disconnect();
                        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void dejTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dejTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dejTextField3ActionPerformed

    private void mnamejTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mnamejTextField1KeyPressed
        // TODO add your handling code here:
        int key=evt.getKeyCode();
        if(key==10)
            cnamejTextField5.requestFocus();
    }//GEN-LAST:event_mnamejTextField1KeyPressed

    private void cnamejTextField5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cnamejTextField5KeyPressed
        // TODO add your handling code here:
        int key=evt.getKeyCode();
        if(key==10)
            dijTextField2.requestFocus();
    }//GEN-LAST:event_cnamejTextField5KeyPressed

    private void dijTextField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dijTextField2KeyPressed
        // TODO add your handling code here:
        int key=evt.getKeyCode();
        if(key==10)
            dejTextField3.requestFocus();
    }//GEN-LAST:event_dijTextField2KeyPressed

    private void dejTextField3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dejTextField3KeyPressed
        // TODO add your handling code here:
        int key=evt.getKeyCode();
        if(key==10)
            qtyjTextField4.requestFocus();
    }//GEN-LAST:event_dejTextField3KeyPressed

    private void qtyjTextField4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qtyjTextField4KeyPressed
        // TODO add your handling code here:
        int key=evt.getKeyCode();
        if(key==10)
            jButton1.requestFocus();
        
        String qty=qtyjTextField4.getText();
      int length= qty.length();
        char c=evt.getKeyChar();
        errjLabel5.setText("");
        if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9')
         qtyjTextField4.setEditable(true);
         else
        {
           
         if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE||evt.getExtendedKeyCode()==KeyEvent.VK_ENTER||evt.getExtendedKeyCode()==KeyEvent.VK_DELETE)       
             qtyjTextField4.setEditable(true);
             
         else{
             qtyjTextField4.setEditable(false);
         errjLabel5.setText("Enter quantity in appropriate manner");
        }}
    }//GEN-LAST:event_qtyjTextField4KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Medicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Medicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Medicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Medicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Medicine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cnamejTextField5;
    private javax.swing.JTextField dejTextField3;
    private javax.swing.JTextField dijTextField2;
    private javax.swing.JLabel errjLabel5;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField mnamejTextField1;
    private javax.swing.JTextField qtyjTextField4;
    // End of variables declaration//GEN-END:variables
}
